### ISSUE TITLE
OPERATOR always asks "Where's Maple?"

### ISSUE THREAD

**Issue by NotAChanceWasTaken** [Celeste-AI/Celeste-AI#7]
Biography Biography Biography Biography Biography Biography Biography Biography Biography Biography

**Comment by OPPEYRADY** [comment]
Where's maple?

**Comment by NotAChanceWasTaken** [comment]
> Where's maple?

I should probably ask you, Where's Celeste?

**Comment by OPPEYRADY** [comment]
On the moon
